# Generated by Django 4.1.5 on 2023-01-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.IntegerField()),
                ('s_fee', models.TextField()),
                ('fee_status', models.IntegerField()),
            ],
        ),
    ]
