# Generated by Django 4.1.5 on 2023-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_fee',
            field=models.IntegerField(),
        ),
    ]
