# Generated by Django 4.1.5 on 2023-01-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('name', models.TextField()),
                ('rollno', models.IntegerField()),
                ('DOB', models.IntegerField()),
            ],
        ),
    ]
