# Generated by Django 4.1.5 on 2023-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_field',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='student_field',
            name='phone_no',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='student_field',
            name='summary',
            field=models.TextField(default='Good Student'),
        ),
    ]
