# Generated by Django 4.1.5 on 2023-01-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0002_student_field_age_student_field_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_field',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='student_field',
            name='age',
            field=models.IntegerField(help_text='your correct age'),
        ),
        migrations.AlterField(
            model_name='student_field',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
